[package]
name = "rust-candle-nn"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = {version = "0.7.2", features = ["cudnn"]}
candle-nn = {version = "0.7.2", features = ["cuda"]}
anyhow = "1.0.89"
rand = "0.8.5"